org.gradle.jvmargs=-Xmx6G -XX:MaxMetaspaceSize=2G -XX:ReservedCodeCacheSize=512m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=false
skipDependencyChecks=true
android.suppressUnsupportedCompileSdk=36
org.gradle.caching=false
org.gradle.configuration-cache=false
org.gradle.parallel=false
android.builtInKotlin=false
android.newDsl=false
